services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - yarn-cache:/usr/local/share/.cache/yarn/v6
      - node_modules:/workspaces/next_study_meeting/node_modules

volumes:
  yarn-cache:
  node_modules:
